---
# tasks file for mnn.nginx-pagespeed

- name: Install apt requirements
  apt: name={{ item }}
  with_items:
    - build-essential
    - zlib1g-dev
    - libpcre3
    - libpcre3-dev
    - unzip

- name: create build path
  file: state=directory
        path={{ nginx_build_dir }}

- block:

  - stat: path={{ nginx_build_dir }}/{{ nginx_pagespeed_url|basename }}
    register: nginx_pagespeed_module

  - name: Download nginx pagespeed module
    get_url: url={{ nginx_pagespeed_url }}
             dest={{ nginx_build_dir }}
             mode=0440

    when: not nginx_pagespeed_module.stat.exists
    register: nginx_pagespeed_module_dl

  - name: unpack nginx pagespeed module
    unarchive: copy=no
               dest={{ nginx_build_dir }}/
               src={{ nginx_pagespeed_module_dl.dest }}
    when: nginx_pagespeed_module_dl.changed
    register: nginx_pagespeed_module_unpack

  - stat: path={{ nginx_build_dir }}/{{ nginx_pagespeed_other_url|basename }}
    register: nginx_pagespeed_psol

  - name: Download other thing
    get_url: url={{ nginx_pagespeed_other_url }}
             dest={{ nginx_build_dir }}

    when: not nginx_pagespeed_psol.stat.exists
    register: nginx_pagespeed_psol_dl

  - name: unpack other thing
    unarchive: copy=no
               dest={{ nginx_build_dir }}/ngx_pagespeed-release-{{ nginx_pagespeed_version }}-beta/
               src={{ nginx_pagespeed_psol_dl.dest }}
    when: nginx_pagespeed_psol_dl.changed
    register: nginx_pagespeed_psol_unpack

  when: nginx_pagespeed_enabled

- stat: path={{ nginx_build_dir }}/{{ nginx_url|basename }}
  register: nginx_source

- name: Download nginx
  get_url: url={{ nginx_url }}
           dest={{ nginx_build_dir }}
  register: nginx_source_dl
  when: not nginx_source.stat.exists

- name: Unpack Nginx
  unarchive: copy=no
             dest={{ nginx_build_dir }}
             src={{ nginx_source_dl.dest }}
  when: nginx_source_dl.changed
  register: nginx_source_unpack

- name: Configure Nginx source
  command: ./configure {{ nginx_build_options_defaults|combine(nginx_build_options)|dict2opts }} --add-module={{ nginx_build_dir }}/ngx_pagespeed-release-{{ nginx_pagespeed_version }}-beta --with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro'
           chdir={{ nginx_build_dir }}/nginx-{{ nginx_version }}
  when: nginx_pagespeed_enabled and
        (nginx_pagespeed_module_unpack|changed or
        nginx_pagespeed_psol_unpack|changed or
        nginx_source_unpack|changed)
  register: nginx_configure_pagespeed

- name: Configure Nginx source
  command: ./configure {{ nginx_build_options_defaults|combine(nginx_build_options)|dict2opts }} --with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro'
           chdir={{ nginx_build_dir }}/nginx-{{ nginx_version }}
  when: not nginx_pagespeed_enabled and
        (nginx_pagespeed_module_unpack|changed or
        nginx_pagespeed_psol_unpack|changed or
        nginx_source_unpack|changed)
  register: nginx_configure

- name: Install Nginx
  shell: make && make install
         chdir={{ nginx_build_dir }}/nginx-{{ nginx_version }}
  when: nginx_configure|changed or nginx_configure_pagespeed|changed
  notify: restart nginx

- name: Install Nginx init script
  template: src=nginx.init
            dest=/etc/init.d/nginx
            mode=755

- name: Create required nginx dirs
  file: path={{ item }}
        state=directory
  with_items:
    - /etc/nginx
    - /var/lib/nginx

- name: Configure Nginx service
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Create sites-enabled
  file: state=directory
        path=/etc/nginx/sites-enabled
